Add validation for service with denied pool by constraints
tsuru/tsuru pull request #2551
Opened 2022-06-13 12:49 UTC by wpjunior

2022-06-14 18:38 UTC, nettoclaudio requested changes
:zap:

2022-06-14 18:38 UTC, nettoclaudio commented on provision/pool/constraint.go
> +		}
WDYT returning an error message with the available services as well? Pretty much like we do in routers validation (see [`ValidateRouters`](https://github.com/tsuru/tsuru/blob/main/provision/pool/pool.go#L247))

2022-06-15 13:11 UTC, wpjunior commented on api/service_instance.go
> +	}
Done @nettoclaudio, thanks for you suggestion

2022-06-17 21:01 UTC, tcarreira approved these changes

2022-06-20 16:12 UTC, nettoclaudio approved these changes
Pretty good refactor. :tada:

2022-06-20 16:50 UTC, merged