Finish job bind feature
tsuru/tsuru pull request #2616
Opened 2023-05-19 14:51 UTC by crgisch

2023-05-19 16:50 UTC, arthurcgc requested changes
This is just half of the review, on Monday I'll revisit this

2023-05-19 16:50 UTC, arthurcgc commented on job/job.go
> +	for i := 0; i < len(job.Spec.ServiceEnvs); i++ {
```suggestion
i := 0
	for _, serviceEnv := range job.Spec.ServiceEnvs {
		if serviceEnv.ServiceName == removeArgs.ServiceName && serviceEnv.InstanceName == removeArgs.InstanceName {
			job.Spec.ServiceEnvs = append(job.Spec.ServiceEnvs[:i], job.Spec.ServiceEnvs[i+1:]...)
			i--
		}
		i++
	}
```

2023-05-19 16:50 UTC, arthurcgc commented on job/job.go
> +	toUnset := lenBefore - len(job.Spec.ServiceEnvs)
```suggestion
	toUnset := lenBefore - i
```

2023-05-29 16:48 UTC, arthurcgc requested changes
There are no unsetJobEnv, unbindJobServiceInstance, bindJobServiceInstance unit tests...

2023-06-01 13:15 UTC, wpjunior approved these changes

2023-06-01 13:21 UTC, merged