provision/kubernetes: add topologySpreadConstraint support
tsuru/tsuru pull request #2619
Opened 2023-05-30 21:17 UTC by morpheu

Add new cluster option "topology-spread-constraints" to specify topology constraints

2023-05-31 00:41 UTC, nettoclaudio requested changes

2023-05-31 00:41 UTC, nettoclaudio commented on provision/kubernetes/helpers.go
> +	}
Why not just decode the JSON into a variable of type `[]apiv1.TopologySpreadConstraint`?

2023-05-31 00:41 UTC, nettoclaudio commented on provision/kubernetes/helpers.go
> +	}
I think doesn't make sense forcing some default values here - such as WhenUnsatisfiable to "ScheduleAnyway". I'd keep only the inclusion of app's labels in the label selector instead.

```suggestion
	for _, c := range topologySpreadConstraintList {
		if c.LabelSelector == nil {
			c.LabelSelector = &metav1.LabelSelector{}
		}

		if c.LabelSelector.MatchLabels == nil {
			c.LabelSelector.MatchLabels = make(map[string]string)
		}

		for k, v := range filterAppLabels(labels) {
			c.LabelSelector.MatchLabels[k] = v
		}
		
		topologySpreadConstraints = append(topologySpreadConstraints, c)
	}
```

2023-05-31 00:41 UTC, nettoclaudio commented on provision/kubernetes/helpers.go
> +	return filteredLabels
Not a big thing, just removing unecessary iteration over app labels.

```suggestion
	filtered := map[string]string{
		tsuruLabelAppName:    labels[tsuruLabelAppName],
		tsuruLabelAppProcess: labels[tsuruLabelAppProcess],
	}

	if v, found := labels[tsuruLabelAppVersion]; found {
		filtered[tsuruLabelAppVersion] = v
	}

	return filtered
```

2023-05-31 17:14 UTC, nettoclaudio approved these changes
lgtm

2023-06-01 19:18 UTC, wpjunior approved these changes

2023-06-01 19:19 UTC, merged