OIDC support
tsuru/tsuru pull request #2632
Opened 2023-07-18 12:50 UTC by wpjunior

2023-07-24 14:34 UTC, nettoclaudio requested changes
It looks good to me at all... I requested some mostly cosmetic changes. 💅

By the way, clever solution to support multi-auth schemes simultaneously. Gonna be important to support switching from one authorization server to another. 🥇

2023-07-24 14:49 UTC, wpjunior commented on auth/oidc/oidc.go
> +	token = strings.TrimPrefix(token, "Bearer ")
not yet, do you thing that is important?

2023-07-24 18:52 UTC, nettoclaudio commented on auth/oidc/oidc.go
> +	token = strings.TrimPrefix(token, "Bearer ")
I think so... it's the way default Tsuru client send it today, look: https://github.com/tsuru/tsuru/blob/f41fb455f8c3903fb947d7bc5e190448a511ac5f/cmd/client.go#L87

2023-07-25 14:37 UTC, nettoclaudio approved these changes
Go for it.

2023-07-25 14:39 UTC, merged