Add new route to get team users and groups
tsuru/tsuru pull request #2636
Opened 2023-08-17 18:23 UTC by wpjunior

2023-08-18 13:43 UTC, nettoclaudio requested changes
Do you mind doc those new routes on OpenAPI file (`docs/reference/api.yaml`)?

2023-08-18 17:09 UTC, wpjunior commented
sure @nettoclaudio, I missed this file, I sent changes now

2023-08-18 18:45 UTC, crgisch commented on api/auth_test.go
> +func (s *AuthSuite) TestTeamGroupsList(c *check.C) {
Could you maybe add some tests for other cases that arent the happy path? (Ex: no permission, no team found...)

2023-08-18 19:45 UTC, wpjunior commented on api/server.go
> +	m.Add("1.16", http.MethodGet, "/teams/{name}/users", AuthorizationRequiredHandler(teamUserList))
could be, but this change does not trigger a break version, them we could use like 1.16.4

2023-08-18 20:14 UTC, crgisch commented on api/server.go
> +	m.Add("1.16", http.MethodGet, "/teams/{name}/users", AuthorizationRequiredHandler(teamUserList))
If we are trying to follow semantic versioning, a new feature would be an increase on a minor version, in this case 1.17.0. An increase to PATCH (major.minor.PATCH) usually means fix(es). Dont want to be picky about it, just some food for thought https://semver.org/

2023-08-21 13:14 UTC, wpjunior commented on api/server.go
> +	m.Add("1.16", http.MethodGet, "/teams/{name}/users", AuthorizationRequiredHandler(teamUserList))
Sure, let's move to 1.17 =)

2023-08-22 19:00 UTC, crgisch approved these changes
LGTM 👍

2023-08-22 19:38 UTC, merged